version: '3'
services: 

  database_server:
    restart: always
    image: 'postgres:9.6-alpine'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  crawler:
    build:
      dockerfile: Dockerfile.dev
      context: ./crawler
    depends_on:
      - database_server
    links:
      - database_server
    volumes:
      - ./crawler:/app
    environment:
      - PGUSER=postgres
      - PGHOST=database_server
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  api:
    build:
      dockerfile: Dockerfile
      context: ./api
    volumes:
      - ./api:/app
    ports:
      - "4000:4000"
    environment:
      - PGUSER=postgres
      - PGHOST=database_server
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432

  front:
    build:
      dockerfile: Dockerfile.dev
      context: ./front
    ports:
      - "3000:3000"
    environment:
      - API_URL=http://localhost:4000/
    volumes:
      - /app/node_modules
      - ./front:/app

volumes:
  db-data:
    driver: local